[package]
name = "gen-unicode"
version = "0.3.0"
authors = ["ridiculousfish <corydoras@ridiculousfish.com>"]
description = "Create Unicode fold tables"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
codegen = "0.2.0"
ucd-parse = "0.1.12"
